// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZB3VaUyWEp3GfJSrVKlLr2Et6EurA8Go',
    appId: '1:169404952251:web:5839ccd83aa455acc5039e',
    messagingSenderId: '169404952251',
    projectId: 'notesapp-7d858',
    authDomain: 'notesapp-7d858.firebaseapp.com',
    storageBucket: 'notesapp-7d858.appspot.com',
    measurementId: 'G-6BCZNNRW3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCONcK3vBX7beN4UTaYi4Sj-j_pxV8FiaM',
    appId: '1:169404952251:android:2981a2a2bb694b79c5039e',
    messagingSenderId: '169404952251',
    projectId: 'notesapp-7d858',
    storageBucket: 'notesapp-7d858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48qoc5neN6z3DNQ6k91NZluZq0RW5yKE',
    appId: '1:169404952251:ios:555ab31e11d0cff1c5039e',
    messagingSenderId: '169404952251',
    projectId: 'notesapp-7d858',
    storageBucket: 'notesapp-7d858.appspot.com',
    androidClientId: '169404952251-48ag3405umi4quufsdkekihs23o617i3.apps.googleusercontent.com',
    iosClientId: '169404952251-kmjsfhspf5uc943k63dvi95nn93pjmup.apps.googleusercontent.com',
    iosBundleId: 'com.lightheads.companion.companion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48qoc5neN6z3DNQ6k91NZluZq0RW5yKE',
    appId: '1:169404952251:ios:555ab31e11d0cff1c5039e',
    messagingSenderId: '169404952251',
    projectId: 'notesapp-7d858',
    storageBucket: 'notesapp-7d858.appspot.com',
    androidClientId: '169404952251-48ag3405umi4quufsdkekihs23o617i3.apps.googleusercontent.com',
    iosClientId: '169404952251-kmjsfhspf5uc943k63dvi95nn93pjmup.apps.googleusercontent.com',
    iosBundleId: 'com.lightheads.companion.companion',
  );
}
